language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install runscript
  - pip install coverage
  - pip install coveralls
  - pip install flake8
  - pip install mock
  - python setup.py develop

script:
  - coverage run --source=captcha_solver -m runscript.cli test

after_success:
  coveralls
