language: python

python: 2.7

matrix:
  include:
    - env: TOX_ENV=py27
      python: 2.7
    - env: TOX_ENV=py34
      python: 3.4
    - env: TOX_ENV=py35
      python: 3.5
    - env: TOX_ENV=py36
      python: 3.6
  exclude:
    - python: 2.7 # hack to exclude default no-env travis job

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

after_success:
  coveralls
