on:
  push:
    branches:
      - Dev

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v2
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        packages-dir: build/dist
        repository-url: https://test.pypi.org/legacy
    - if: startsWith(github.ref, 'refs/heads/Prod')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        packages-dir: build/dist