on: push

env:
  FILES: ../src/humanoid

defaults:
  run:
    shell: bash
    working-directory: ./build

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.11']
    steps:

    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install Dependencies
      run: |
        PYTHON_BIN="${pythonLocation:+$pythonLocation/bin/python}"
        PYTHON_BIN="${PYTHON_BIN:-python}"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        "$PYTHON_BIN" -m pip install --upgrade pip
        "$PYTHON_BIN" -m pip install -U -r requirements/build.txt
        "$PYTHON_BIN" -m pip install -U -r requirements/run.txt
        "$PYTHON_BIN" -m pip install -U -r requirements/dev.txt
        "$PYTHON_BIN" -m pip install -U -e .

    - name: Run static checks
      run: |
        PYTHON_BIN="${pythonLocation:+$pythonLocation/bin/python}"
        PYTHON_BIN="${PYTHON_BIN:-python}"
        # pylint -j0 $(FILES)
        # flake8 -j auto --max-cognitive-complexity=17 $(FILES)
        # bandit -qc pyproject.toml -r $(FILES)
        MYPYPATH=../src "$PYTHON_BIN" -m mypy --strict --explicit-package-bases "$FILES"
