on: push

defaults:
  run:
    shell: bash
    working-directory: ./build

jobs:
  test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.12']
    steps:

    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        PYTHON_BIN="${pythonLocation:+$pythonLocation/bin/python}"
        PYTHON_BIN="${PYTHON_BIN:-python}"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        "$PYTHON_BIN" -m pip install --upgrade pip
        "$PYTHON_BIN" -m pip install --no-build-isolation -r requirements/build.txt
        "$PYTHON_BIN" -m pip install --no-build-isolation -r requirements/run.txt
        "$PYTHON_BIN" -m pip install --no-build-isolation -r requirements/dev.txt
        "$PYTHON_BIN" -m pip install --no-build-isolation --editable .

    - name: Run tests
      run: |
        PYTHON_BIN="${pythonLocation:+$pythonLocation/bin/python}"
        PYTHON_BIN="${PYTHON_BIN:-python}"
        "$PYTHON_BIN" -m pytest ../src/humanoid/tests

  test_install_package:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.12']
    steps:

    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install Humanoid
      run: |
        PYTHON_BIN="${pythonLocation:+$pythonLocation/bin/python}"
        PYTHON_BIN="${PYTHON_BIN:-python}"
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        "$PYTHON_BIN" -m pip install --upgrade pip
        "$PYTHON_BIN" -m pip install .
        "$PYTHON_BIN" -m pip install -r requirements/dev.txt

    - name: Run tests
      run: |
        PYTHON_BIN="${pythonLocation:+$pythonLocation/bin/python}"
        PYTHON_BIN="${PYTHON_BIN:-python}"
        "$PYTHON_BIN" -m pytest ../src/humanoid/tests
