on: push

defaults:
  run:
    shell: bash
    working-directory: ./build

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.12']
    permissions:
      id-token: write
    steps:

    - uses: qoomon/actions--access-token@v3
      id: access-token
      with:
        repository: ArtificialHumanoid/Utilities
        permissions: |
          contents: read
    
    - uses: actions/checkout@v4

    - uses: actions/checkout@v4
      with:
        repository: ArtificialHumanoid/Utilities
        path: Utilities
        token: ${{ steps.access-token.outputs.token }}

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      env:
        GITHUB_TOKEN: ${{ steps.access-token.outputs.token }}
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        curl https://bootstrap.pypa.io/get-pip.py | python3
        pip install -U -r requirements_dev.txt

    - name: Run tests
      run: |
        python -c "from utilities.meta.testing_of.packages.test.importation import import_all"
